export { default as Cart } from './Cart'
export { default as History } from './History/'
export { default as Home } from './Home'
export { default as Profile } from './Profile/'
export { default as Sector } from './Sector'
export { default as Brand } from './Brand'
export { default as Detail } from './Detail'
